# SUBWAY
## TO-DO


# STREETCAR 
##'location' column mapping
sc_locations_mapping = {
    '': ['\\','/','-','(',')','.',',','&', "'",'and', '@','`','[', ']', 'line','route', 'blvd','at','to'],
    'station': ['stn', 'stion'],
    'road': [' rd'],
    ' street': [' str'],
    'bathurst': ['bhurst'], 
    'dundas west station': ['dws','dundas w stn', 'dundas west stion', 'dundas west stn', 'dw station', 'dundas w station', ], 
    'neville loop': ['neville park', 'neville park loop'], 
    'roncesvalles': ['roncy', 'roncesvallesqueen'],
    'st clair': ['st claire', 'stclair'],
    'nan': ['no location'],
    'bathurst college': ['bathurstcollege'],  
    'bathurst dundas': ['bathurstdundas'],
    'bathurst fleet': ['bathurstfleet'], 
    'bathurst king': ['bathurstking'], 
    'bathurst queen': ['bathurstqueen'], 
    'bathurst st clair': ['bathurstst clair'],
    'broadview danforth': ['broadviewdanforth'], 
    'broadview dundas': ['broadviewdundas'],
    'broadview gerrard': ['broadviewgerrard'], 
    'broadview millbrook': ['broadviewmillbrook'], 
    'broadview withrow': ['broadviewwithrow'],
    'broadview queen': ['broadviewqueen'], 
    'broadview': ['brodview'],
    'college bathurst': ['collegebathurst'],
    'college bay': ['collegebay'],
    'college lansdowne': ['collegelansdowne'],
    'college mccaul': ['collegemccaul'],
    'college ossingn': ['collegeossingn'],
    'college spadina': ['collegespadina'],
    'college university': ['collegeuniversity'], 
    'distillery': ['distillary', 'distrillery', 'disterilly'],
    'landsdowne:': ['lansdown', 'landsdownee'],
    'parliament': ['parlament'], 
    'sherbourne': ['sherborne'],
    'king bathurst':['kingbathurst'],
    'king bay':['kingbay'],
    'king brant':['kingbrant'],
    'king charlotte':['kingcharlotte'],
    'king church':['kingchurch'],
    'king dowling':['kingdowling'],
    'king dufferin':['kingdufferin'],
    'king dunn':['kingdunn'],
    'king duoro':['kingduoro'],
    'king jameson':['kingjameson'],
    'king jameson kingjarvis':['kingjameson kingjarvis'],
    'king jarvis':['kingjarvis'],
    'king john':['kingjohn'],
    'king lantic':['kinglantic'],
    'king niagara':['kingniagara'],
    'king ontario':['kingontario'],
    'king parliament':['kingparliament'],
    'king peter':['kingpeter'],
    'king portl':['kingportl'],
    'king queen':['kingqueen'],
    'king river':['kingriver'],
    'king roncesvalles':['kingroncesvalles'],
    'king shaw':['kingshaw'],
    'king sherbourne':['kingsherbourne'],
    'king simcoe':['kingsimcoe'],
    'king sn loop':['kingsn loop'],
    'king sn queen':['kingsn queen'],
    'king sn rd':['kingsn rd'],
    'king sn rd loop':['kingsn rd loop'],
    'king sn rd queen':['kingsn rd queen'],
    'king sn rd woodbine':['kingsn rd woodbine'],
    'king sn road':['kingsn road'],
    'king sn road loop':['kingsn road loop'],
    'king sn road queen':['kingsn road queen'],
    'king sn woodbine':['kingsn woodbine'],
    'king spadina':['kingspadina'],
    'king strachan':['kingstrachan'],
    'king sumach':['kingsumach'],
    'king university':['kinguniversity'],
    'king vicria':['kingvicria'],
    'king yonge':['kingyonge'],
    'king york':['kingyork'],
    'dundas bathurst':['dundasbathurst'],
    'dundas bay':['dundasbay'],
    'dundas bloor':['dundasbloor'],
    'dundas broadview':['dundasbroadview'],
    'dundas brock':['dundasbrock'],
    'dundas church':['dundaschurch'],
    'dundas dufferin':['dundasdufferin'],
    'dundas euclid':['dundaseuclid'],
    'dundas huron':['dundashuron'],
    'dundas jarvis':['dundasjarvis'],
    'dundas lansdowne':['dundaslansdowne'],
    'dundas ossingn':['dundasossingn'],
    'dundas parlament':['dundasparlament'],
    'dundas parliament':['dundasparliament'],
    'dundas river':['dundasriver'],
    'dundas sackville':['dundassackville'],
    'dundas spadina':['dundasspadina'],
    'dundas university':['dundasuniversity'],
    'queen augusta':['queenaugusta'],
    'queen bathurst':['queenbathurst'],
    'queen bay':['queenbay'],
    'queen brdv':['queenbrdv'],
    'queen broadview':['queenbroadview'],
    'queen cannaught':['queencannaught'],
    'queen carlaw':['queencarlaw'],
    'queen carroll':['queencarroll'],
    'queen church':['queenchurch'],
    'queen connaught':['queenconnaught'],
    'queen coxwell':['queencoxwell'],
    'queen dovercourt':['queendovercourt'],
    'queen dufferin':['queendufferin'],
    'queen greenwood':['queengreenwood'],
    'queen jarvis':['queenjarvis'],
    'queen john':['queenjohn'],
    'queen jones':['queenjones'],
    'queen king':['queenking'],
    'queen kingsn rd':['queenkingsn rd'],
    'queen lansdowne':['queenlansdowne'],
    'queen leslie':['queenleslie'],
    'queen logan':['queenlogan'],
    'queen mccaul':['queenmccaul'],
    'queen ossingn':['queenossingn'],
    'queen pape':['queenpape'],
    'queen parliament':['queenparliament'],
    'queen peter':['queenpeter'],
    'queen river':['queenriver'],
    'queen roncesvalles':['queenroncesvalles'],
    'roncesvalles dundas':['roncesvallesdundas'],
    'roncesvalles garden':['roncesvallesgarden'],
    'roncesvalles howard park':['roncesvalleshoward park'],
    'roncesvalles marion':['roncesvallesmarion'],
    'roncesvalles sway':['roncesvallessway']
}

##'direction' mapping
sc_direction_map = {
    '': ['\\','/','-','(',')','.',',','&', "'",'and', '@','`','[', ']', "#"],
    'both': ['bw'], 
    'n': ['n/b', 'nb', 'northbound'],
    'e': ['e/b', 'eb', 'ew', 'e/w', 'eastbound'],
    's': ['s/b', 'sb', 'southbound'],
    'w': ['w/b', 'wb', 'westbound', 'we',r'w\b', 'w.b']
}

# BUS
bus_locations_mapping = {
    '': ['\\','/','-','(',')','.',',','&', "'",'and', '@','`','[', ']', 'line','route', 'blvd','at','to'],
    'station': ['stn', 'stion'],
    'road': [' rd'],
    ' street': [' str'], 
    'entire': ['all of', 'all locions', 'all along the', 'all run affected'],
    'eglinton': ['eglinn','egli ','egl '], 
    ' west': [' w '], 
    'bathurst': ['bhurst']
    }

bus_direction_map = {
    '': ['\\','/','-','(',')','.',',','&', "'",'and', '@','`','[', ']', "#"],
    'both': ['bw', 'b/w', 'boths', 'bothways', 'both ways', 'bothway', 'bothays', 'b w' 'both1'], 
    'n': ['n/b', 'nb', 'northbound', 'up', 'north'],
    'e': ['e/b', 'eb', 'ew', 'e/w', 'eastbound', 'east'],
    's': ['s/b', 'sb', 'southbound', 'down', 'south'],
    'w': ['w/b', 'wb', 'westbound', 'we',r'w\b', 'w.b', 'wst']
}